version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    restart: always  # Automatically restarts on failure or reboot
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movie_reservation
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

