/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Movie } from '../models/movie';
export interface Genre {
  id?: number;
  movies?: Array<Movie>;
  name?: string;
}
