/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Genre } from '../models/genre';
import { Showtime } from '../models/showtime';
export interface Movie {
  description?: string;
  genre?: Genre;
  id?: number;
  imageUrl?: string;
  showtimes?: Array<Showtime>;
  title?: string;
}
