/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Seat } from '../models/seat';
import { Showtime } from '../models/showtime';
export interface Room {
  id?: number;
  name?: string;
  seats?: Array<Seat>;
  showtimes?: Array<Showtime>;
}
