/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Reservation } from '../models/reservation';
import { Room } from '../models/room';
export interface Seat {
  id?: number;
  reservations?: Array<Reservation>;
  room?: Room;
  seatNumber?: string;
}
