/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Movie } from '../models/movie';
import { Room } from '../models/room';
export interface Showtime {
  endTime?: string;
  id?: number;
  movie?: Movie;
  room?: Room;
  startTime?: string;
}
