/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Reservation } from '../models/reservation';
export interface User {
  email?: string;
  id?: number;
  password?: string;
  reservations?: Array<Reservation>;
  role?: 'USER' | 'ADMIN';
  username?: string;
}
