/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface CreateReservation$Params {
  userId: number;
  showtimeId: number;
  seatIds: Array<number>;
}

export function createReservation(http: HttpClient, rootUrl: string, params: CreateReservation$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, createReservation.PATH, 'post');
  if (params) {
    rb.query('userId', params.userId, {});
    rb.query('showtimeId', params.showtimeId, {});
    rb.query('seatIds', params.seatIds, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

createReservation.PATH = '/reservations';
